### ISSUE TITLE
Implement QueryInterface

### ISSUE THREAD

**Issue by aldenquimby** [getsentry/raven-java#116]
http://sentry.readthedocs.org/en/latest/developer/interfaces/index.html#sentry.interfaces.query.Query

similar to https://github.com/getsentry/raven-java/issues/110

**Comment by tkaemming** [comment]
Updated documentation link: https://docs.getsentry.com/hosted/clientdev/interfaces/#context-interfaces

For context, we still don't really do anything particularly useful on the server side, as mentioned in getsentry/sentry#1097: https://github.com/getsentry/sentry/blob/master/src/sentry/interfaces/query.py

**Comment by tkaemming** [comment]
I don't think we have any plans to implement this in the near future on the server side, so I'm going to close this (for now at least.)
