### ISSUE TITLE
Modifying the request before sending to sentry. 

### ISSUE THREAD

**Issue by anujku** [getsentry/raven-java#132]
I want to modify the request before sending to sentry. I want to check some params from the request. Some of the request that is captured is missing the body. Also I want to exclude some params from the request.

How is the request captured from the loggingevent with Raven Java ? `HttpConnection.doSend()` ? 

Is it possible to modify this request ? Modifying `RavenServletRequestListener.servletRequest`  ?

**Comment by tkaemming** [comment]
@anujku - I think this comment will address your questions: https://github.com/getsentry/raven-java/issues/162#issuecomment-164921702
