### ISSUE TITLE
Wrongful data sanitization?

### ISSUE THREAD

**Issue by dmk23** [getsentry/raven-java#133]
I've upgraded Sentry to 7.4.1 and raven-java to 6.0.0. While everything seemed to function I noticed that some of the fields are now improperly sanitized/treated as passwords (replaced with ```********```).

Specifically I am seeing this with timer fields named ```time_start``` and ```time_end``` and storing ```Long.toString(System.currentTimeMillis())```. However a field named ```time_ms``` storing the difference between these ms timestamps gets recorded properly without sanitization.

I am not seeing this kind of behavior with anything in the raven python client so I figure this has to be something with the latest release of the java client. Is this something that could be addressed by client configuration or there might be an actual bug somewhere?

**Comment by tkaemming** [comment]
@dmk23 - I wasn't able to find anywhere in the codebase where this would be occurring, so I'm going to close this. (I'm not totally familiar with the codebase yet, so I could be wrong — but a quick scan of anywhere I'd expect it to be didn't turn up anything.)

If you're still experiencing this issue on the [Sentry 8.0.0rc1 server](https://pypi.python.org/pypi/sentry/8.0.0rc1), can you open a ticket on [getsentry/sentry](https://github.com/getsentry/sentry) with an example payload that is being scrubbed?
