### ISSUE TITLE
Cannot connect to Sentry 5.0.21

### ISSUE THREAD

**Issue by galihtias** [getsentry/raven-java#135]
Hi, following this example : https://github.com/getsentry/raven-java/tree/master/raven-log4j

my app are web app (java) that has use log4j for logging,
my server are Sentry 5.0.21
my app web server are tomcat 7.55

I try the example above but doesn't have any email (but other old log are working) and it doesn't give any error.
can someone please tell me where to find what wrong

this my log4j.properties
"
# Root logger option
log4j.rootLogger=DEBUG,  stdout

# Raven
log4j.category.RavenLog= DEBUG, SentryAppender

#redirect to email
log4j.appender.SentryAppender=net.kencochrane.raven.log4j.SentryAppender
log4j.appender.SentryAppender.dsn=http://6263d6e967664d1eb697b510564c3314:46f8bc67a10f47498b002aa6ece99e69@192.168.10.217:9000/2
log4j.appender.SentryAppender.tags=tag1:value1,tag2:value2

# Redirect log messages to console
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
"

this my java class : 
"
.....
private final Logger logger = Logger.getLogger(OrganizationRestService.class);
private final Logger logEmail = Logger.getLogger("RavenLog");
.....
if(logEmail.isDebugEnabled()){
            logEmail.debug("Test Page Hello");
        }
        logEmail.info("This is a test");
        logEmail.error("Exception caught");
"

**Comment by dcramer** [comment]
Do you really mean the Sentry server is 5.x? If so you need to upgrade it.

**Comment by galihtias** [comment]
@dcramer 
yups, 5.x.
I wanna do that but i cannot (for now) is there any other solution?

**Comment by galihtias** [comment]
i update to Sentry 7.4.1, but still connot connect from my java app.

**Comment by dcramer** [comment]
This is most certainly an issue with the server configuration (unrelated to raven-java most likely).

You should ensure you have maximum logging and all things are running (i.e. workers, redis configured, etc). You can run workers with -l INFO to increase logging, and as long as the client isn't returning an error (i.e. it gets a 200) its 100% a server misconfiguration.
