### ISSUE TITLE
error in documentation of raven-log4j

### ISSUE THREAD

**Issue by wiselynx** [getsentry/raven-java#136]
In the README.md file for raven-log4j, there is an error in the "Mapped tags" paragraph. The line reporting:

    log4j.appender.SentryAppender.mappedTags=User,OS

should report instead:

    log4j.appender.SentryAppender.extraTags=User,OS

**Comment by buckett** [comment]
Yeah, mappedTags aren't used at all.

**Comment by dcramer** [comment]
Theres a bunch of slips in this one. I'm going to get a PR up.
