### ISSUE TITLE
Do not working <ravenFactory> elements in log4j2.xml by raven-java-log4j2

### ISSUE THREAD

**Issue by suhyunjeon** [getsentry/raven-java#143]
Hello, I am a newbie Sentry. It really good for me open source.

Let's me ask you guys a question.

I setting up my project by raven-java-log4j2.

- Using libs
1. raven-6.0.0.jar
2. raven-log4j2-6.0.0.jar
3. log4j-api-2.3.jar
4. log4j-core-2.3.jar
5. log4j-1.2-api-2.3.jar

- log4j2.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="info" packages="org.apache.logging.log4j.core,net.kencochrane.raven.log4j2,net.kencochrane.raven.servlet">

    <Appenders>       
        <Console name="STDOUT" target="SYSTEM_OUT">
            <PatternLayout pattern="%d %-5p [%t] %C{2} (%F:%L) - %m%n"/>
        </Console>
        <Raven name="Sentry">
            <dsn>xxxxx</dsn>
            <ravenFactory>net.kencochrane.raven.DefaultRavenFactory</ravenFactory>
            <tags>name:tasha</tags>
            <extraTags>abc,def</extraTags>
        </Raven>
    </Appenders>

    <Loggers>      
        <Root level="trace">
            <appender-ref ref="STDOUT"/>
        </Root>
        <Root level="info">
            <appender-ref ref="Sentry"/>
        </Root>
    </Loggers>
</Configuration>
```

 
Do not working <ravenFactory> elements in log4j2.xml by raven-java-log4j2.

I want to see User information(marshaller.addInterfaceBinding(UserInterface.class, new UserInterfaceBinding()))
There are only Tag | Stacktrace | Additional Data. 

How do I do? Help me please.
Have a nice day!

**Comment by suhyunjeon** [comment]
I solved the problem like this.
```
        <Root level="info">
            <appender-ref ref="STDOUT"/>
            <appender-ref ref="Sentry"/>
        </Root>
```

**Comment by tkaemming** [comment]
I'm not quite sure what the question is here, but it looks like you found a solution — let us know if there is anything else we can do to help.
