### ISSUE TITLE
Does not log filename

### ISSUE THREAD

**Issue by mikelikespie** [getsentry/raven-java#153]
I noticed in the code there is

```
        // Do not display the file name (irrelevant) as it replaces the module in the sentry interface.
        //generator.writeStringField(FILENAME_PARAMETER, stackTraceElement.getFileName());
```

However, in the Sentry UI, it never shows the filename where an exception occurred which makes it really difficult to use.

**Comment by dcramer** [comment]
I think the right approach here is to fix this in the Sentry API, and undo this change upstream.

To me it makes sense to prioritize modules over filenames. If we did that in the UI would that cause problems here?

i.e. if you specify both a filename and a module, module shows, otherwise it shows filename

**Comment by mikelikespie** [comment]
@dcramer It seems it would be ideal to show both similar to how a java stack trace does.

It formats the lines like

```
com.squareup.service.framework.request.AbstractInvocation.proceed(AbstractInvocation.java:78)
```

The nice thing about having the `<filename>:<line number>` is that one can copy & paste that string and use quick-open in editors like xcode and intellij and go right to the file and the line

**Comment by dcramer** [comment]
@mikelikespie fair point, though I'm not sure we want to go full on like that (as it limits our UI capabilities). We *should* be doing that via the raw view already.

That said I think we can still do module (base filename) in the rich view.

Does that sound like a reasonable solution?

**Comment by mikelikespie** [comment]
Yeah that sounds good to me.

**Comment by dcramer** [comment]
Played w/ this a bit -- it'll be a bit of a challenge to make it fit nicely (its more work than just adding the module name in addition to filename).

That said I'm on board w/ this change in raven-java since we can tweak it on the server

**Comment by dcramer** [comment]
@mikelikespie I'm ok with the change. Mind submitting a PR?
