### ISSUE TITLE
Unclear how to send a User context object with log4j2

### ISSUE THREAD

**Issue by inversion** [getsentry/raven-java#162]
Hi, I can't figure out how to send a user context object with an id using the log4j2 library.

The MDC example at https://github.com/getsentry/raven-java/tree/master/raven-log4j2#mapped-tags suggests using `extraTags`. But this example only sends a `"test user"` string. How about if I want to send a user object with `id`, `email` and `name`?

In addition, do I have to set the User context programatically using MDC, or is there a way to predefine it in the `log4j2.xml` configuration?

**Comment by pwielgolaski** [comment]
I think RavenServletRequestListener could be interesting for you

**Comment by tkaemming** [comment]
We generally don't recommend adding user context to specific logger calls but instead using [`EventBuilderHelper`](https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/net/kencochrane/raven/event/helper/EventBuilderHelper.java) to track authentication state during a typical request/response cycle. [`HttpEventBuilderHelper`](https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/net/kencochrane/raven/event/helper/HttpEventBuilderHelper.java) is an example of this pattern, as @pwielgolaski alluded to with [`RavenServletRequestListener`](https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/net/kencochrane/raven/servlet/RavenServletRequestListener.java).

If the standard `HttpEventBuilderHelper` doesn't fit your needs, you can set up additional builders by overriding or extending the `DefaultRavenFactory` — specifically the [`createRavenInstance` method](https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/net/kencochrane/raven/DefaultRavenFactory.java#L64-L74). The logger integrations generally have a configuration option to use a different factory class — [`ravenFactory` in the case of log4j2](https://github.com/getsentry/raven-java/tree/master/raven-log4j2#configuration).

In the case of MDC, [only `String` values are supported](http://www.slf4j.org/api/org/slf4j/MDC.html#put(java.lang.String, java.lang.String)) which doesn't really provide a suitable representation for composite data types like the `User` interface. We should probably remove that example from the documentation for clarity's sake.

Hope this helps!
