### ISSUE TITLE
Publish release for 6.0.1.

### ISSUE THREAD

**Issue by tkaemming** [getsentry/raven-java#163]
@ColinHebert - Do you mind releasing master as 6.0.1 so that #161 is fixed in the release on Maven Central?

c8a5266bd57823da58885f56f383b65a900cf64d could also be cherry-picked into the 5.x maintenance branch. I skipped this due to the two-version from current maintenance policy since the server is now technically on protocol version 7. Version 5 is still supported, though, so it might make sense to release that as well.

Also, I'm not sure what the common workflow is for getting added as a publisher for Maven Central, but it might also be a good idea for me to go ahead and get that set up if you could point me in the right direction.

Thanks!

**Comment by dcramer** [comment]
fyi @tkaemming is the guy at Sentry that we made learn Java ;)

**Comment by xolvo** [comment]
If I were you, I'd release 6.0.1 with commit c8a5266 only. And after that release 7.0.0 with all new features support for Sentry 8. So project will respect semver.

**Comment by bclermont** [comment]
Or release a 6.0.2 with latest version of everything

:+1:  for Sentry 8 support

**Comment by jasonculverhouse** [comment]
Bump....   It seems that  the 6.0.1-SNAPSHOT has disappeared from maven repositories... https://oss.sonatype.org/#nexus-search;quick~raven-log4j

**Comment by tkaemming** [comment]
The 6.0.1-SNAPSHOT release should still be available in the Sonatype Snapshot repository: https://oss.sonatype.org/content/repositories/snapshots/net/kencochrane/raven/raven-log4j2/6.0.1-SNAPSHOT/

Details on how to use the snapshot repositories are here: https://github.com/getsentry/raven-java#snapshot-versions

We're going to be moving this over to `com.getsentry` very soon so that we have control over publishing and to clarify this is the officially supported Raven client for Java. We'll get back onto a normal release cycle at that point.

**Comment by tkaemming** [comment]
Closing this, as GH-182 is going to result in version 7.
