### ISSUE TITLE
remote address reported incorrectly when behind a proxy

### ISSUE THREAD

**Issue by j-fernandes** [getsentry/raven-java#164]
When an instance is behind a proxy, the reported Environment.REMOTE_ADDR is incorrect - it gives the ip of the load balancer instead of the caller.

Can be fixed by changing the interface to use the 'x-forwarded-header' first and picking the head of the list; and then using getRemoteAddr call only in the event the header is not present, like so:

    private static String headAddress(String ls) {
        List<String> ips = Arrays.asList(ls.split("\\s*,\\s*"));
        return ips.get(0);
    }

    public static String getForwardedRemoteAddr(HttpServletRequest req)  {
        String forwared = req.getHeader("X-FORWARDED-FOR");
        if (forwared == null) {
            String remote = req.getRemoteAddr();
            return headAddress(remote);
        }
        return headAddress(forwared);
    }

Cheers

**Comment by j-fernandes** [comment]
Tried forking and submitting a pull req but Git keeps saying there are no diffs even when there are, so gave up. Here is a summary of changes

![164](https://cloud.githubusercontent.com/assets/16024327/11412239/004f2ba2-9426-11e5-86a8-e198b1cba0af.png)

**Comment by tkaemming** [comment]
@j-fernandes - We're not confident enabling this in all situations (as in this patch), but we agree that this is something we need to offer without having to write custom code to do it. (For context, our rationale is similar to the one described here: https://docs.djangoproject.com/en/dev/releases/1.1/#removed-setremoteaddrfromforwardedfor-middleware) We're going to implement this as something that can be enabled with a setting passed to Raven, and it should be in on the `master` branch and `SNAPSHOT` release sometime this week.

**Comment by tkaemming** [comment]
For parity with `raven-python`, if the hostname is resolved using an alternate resolution method (`X-Forwarded-For`) this should also rewrite the URL hostname ([implemented here](https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/net/kencochrane/raven/event/interfaces/HttpInterface.java#L39)) with the resolved hostname.

**Comment by bretthoerner** [comment]
Fixed link for URL hostname for posterity: https://github.com/getsentry/raven-java/blob/63b1d551e096cb8a438997c8f546eb8b7b0d7639/raven/src/main/java/net/kencochrane/raven/event/interfaces/HttpInterface.java#L39

I've opend https://github.com/getsentry/raven-java/pull/192 which is your change, @tkaemming, updated to master and compiling (checkstyle issues). Can you give me a pointer to what you mean about `raven-python` parity? I'm rusty. :(

**Comment by tkaemming** [comment]
> For parity with raven-python, if the hostname is resolved using an alternate resolution method (X-Forwarded-For) this should also rewrite the URL hostname (implemented here) with the resolved hostname.

This was a comment about X-Forwarded-*Host* (not X-Forwarded-*For*), I'm not really sure what I was talking about here (or why…?)

**Comment by bretthoerner** [comment]
https://github.com/getsentry/raven-java/commit/c5f9e2d4f0d2fca8b6d54b520c8aa997bbef1fd7
