### ISSUE TITLE
Support `release` attribute for all appender configurations.

### ISSUE THREAD

**Issue by dcramer** [getsentry/raven-java#171]
We need to ensure that the [`release` attribute](https://docs.getsentry.com/hosted/clientdev/attributes/) is a supported configuration option for each appender implementation, and is documented (if feasible.)

- [x] JUL: GH-185
- [x] Log4J: GH-158
- [x] Log4J2: GH-185
- [x] Logback: GH-154

**Comment by tkaemming** [comment]
A log4j patch is here: #158 (I haven't reviewed it yet.)

**Comment by tkaemming** [comment]
This was added for logback in #154.

**Comment by kynalvarus** [comment]
Any update on log4j2 SentryAppender support for release?

**Comment by bretthoerner** [comment]
`jul` and `log4j2` in this PR: https://github.com/getsentry/raven-java/pull/185

**Comment by tkaemming** [comment]
@bretthoerner think it makes sense to cut 7.1 with these changes?
