### ISSUE TITLE
InetAddress.getLocalHost().getCanonicalHostName() does not work in Java 7

### ISSUE THREAD

**Issue by siddjain** [getsentry/raven-java#175]
https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/net/kencochrane/raven/event/EventBuilder.java#L556:
```
private static final class HostRetriever implements Callable<String> {
            @Override
            public String call() throws Exception {
                return InetAddress.getLocalHost().getCanonicalHostName();
            }
        }
```
Above code causes error in Java 7. The issue is documented here:
http://stackoverflow.com/questions/19864388/why-does-this-usage-of-inetaddress-getlocalhost-work-okay-with-java-6-but-fail
Could this method be fixed so that it uses some other means to get the hostname?

**Comment by bretthoerner** [comment]
The `serverName` can be set statically after: https://github.com/getsentry/raven-java/pull/195

This entirely avoids the `HostRetriever` (and `HostnameCache`).
