### ISSUE TITLE
Support for HTTP proxying of event emissions?

### ISSUE THREAD

**Issue by jszwedko** [getsentry/raven-java#176]
It looks like support existed at one point (https://github.com/getsentry/raven-java/pull/1), but the code has changed a lot since then, and it doesn't currently seem to be supported. It seems like it would support could be added by passing a proxy here: https://github.com/getsentry/raven-java/blob/fd5a44c11d851180909ab7fe8c23cc3dc7773617/raven/src/main/java/net/kencochrane/raven/connection/HttpConnection.java#L101 via https://docs.oracle.com/javase/7/docs/api/java/net/URL.html#openConnection(java.net.Proxy).

I'm envisioning that the proxy settings could be set as additional `GET` params on the DSN, e.g.: `https://public:private@host:port/1?http_proxy_host=127.0.01&http_proxy_port=1234`, but wanted to get feedback on this approach before submitting a pull request (which I am more than happy to do). Another approach could be modifying `RavenFactory` to add another constructor accepting the proxy arguments.

Please let me know if I'm missing something and that this is already supported.

/cc @mnussbaum

**Comment by tkaemming** [comment]
This seems reasonable to me. I'd use the query parameters on the DSN as you mentioned (probably `raven.http.proxy.host` and `raven.http.proxy.port` for consistency with the style of the other configuration parameters) rather than modifying the factory.

**Comment by jszwedko** [comment]
@tkaemming so we tried again today, and it turns out that the `java.net` APIs used actually do support `-Dhttps.proxyHost` and `-Dhttps.proxyPort` -- I think we may have been typoing the properties.

Given that, I think we can just document this in the `README.md` -- we can put together a PR for that.

**Comment by tkaemming** [comment]
I think it's OK to reopen this one (specifically to allow providing a `Proxy` instance to `HttpConnection`.)

**Comment by cyrilmhansen** [comment]
Hi, is someone already working on this ? Are you open to an external contribution ?

**Comment by bretthoerner** [comment]
I haven't started on anything. We're definitely open to contributions.

**Comment by bretthoerner** [comment]
Just a heads up, I have a PR up that I'll be finishing today.

**Comment by bretthoerner** [comment]
Merged this, will be publishing with 7.5.0 soon.
