### ISSUE TITLE
Cant get extraTags working in log4j.xml

### ISSUE THREAD

**Issue by janpickard** [getsentry/raven-java#177]
Hi there,

I am trying to use the extraTags in log4j.xml but it is not taking affect. Is there an issue with my config or is there a possible bug?

The MDC data is appearing in sentry but under additional data but not on the right as tags

`<appender name="sentry" class="net.kencochrane.raven.log4j.SentryAppender">
            <param name="dsn" value="https://excluded/" />
           <param name="extraTags" value="User,Company,Email,ID" />
            <filter class="org.apache.log4j.varia.LevelRangeFilter">
                <param name="levelMin" value="WARN"/>
            </filter>
</appender>`

**Comment by tkaemming** [comment]
I don't see anything wrong with the configuration and I was able to replicate the intended behavior using a similar configuration and an adaptation of our [log4j example project](https://github.com/getsentry/raven-java-examples/tree/master/raven-java-log4j-example) that included two MDC values.

```
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">
<log4j:configuration xmlns:log4j="http://jakarta.apache.org/log4j/">
    <appender name="sentry" class="net.kencochrane.raven.log4j.SentryAppender">
        <param name="extraTags" value="foo,bar" />
    </appender>
    <root>
        <priority value="debug" />
        <appender-ref ref="sentry" />
    </root>
</log4j:configuration>
```
