### ISSUE TITLE
ServiceLoader not working in JBoss EAP 6

### ISSUE THREAD

**Issue by cdietze** [getsentry/raven-java#178]
This issue probably also applies to JBoss Wildfly 7.x from which EAP6 is derived.

We install raven-java as a JBoss Module (JBM) so we can configure the JUL-Logger in the central config file.
However, there are some specialties in JBoss when it comes to ClassLoaders ... and the ServiceLoader that is used to find instances of `RavenFactory`s finds nothing.
I did some debugging and the reason is that `ServiceLoader.load(RavenFactory.class)` will use `Thread.currentThread().getContextClassLoader()` which in my case is a `org.jboss.modules.ModuleClassLoader` for a different JBM (`org.jboss.as.server`). And that one does not find any `RavenFactory` instances.

If I call `ServiceLoader.load(RavenFactory.class, RavenFactory.class.getClassLoader())` it works find and discovers the `DefaultRavenFactory`.

Just discovered a PR that fixes exactly that, yet for another reason: #129 

So this is my +1 to merge that PR

**Comment by tkaemming** [comment]
This will be part of the 7.0.1 release.
