### ISSUE TITLE
support for jdk 6

### ISSUE THREAD

**Issue by ramesh4sr** [getsentry/raven-java#200]
Do we have support for jdk 6? A lot of applications are still running on jdk 6.

**Comment by bretthoerner** [comment]
Good question, I'll check it out.

**Comment by ramesh4sr** [comment]
Please let me know if this makes sense. I can help, did some changes locally to make it work for us.

**Comment by bretthoerner** [comment]
What all did you have to change? I was taking a stab at downgrading the source/target to `1.6` but think our testing deps might require 7. https://github.com/getsentry/raven-java

**Comment by ramesh4sr** [comment]
90% of changes are due to empty set of type parameters <> which isn't supported below 1.7

**Comment by bretthoerner** [comment]
Yeah, that's most of what my branch is. But did you get the tests passing?

**Comment by ramesh4sr** [comment]
yes i was able to, i had to disable checkstyle, it couldn't find suppresions.xml.
[buildOutput.txt](https://github.com/getsentry/raven-java/files/222815/buildOutput.txt)

**Comment by bretthoerner** [comment]
@ramesh4sr but were you using JDK 6 to run the tests? TestNG requires JDK 7+

I can use Java 7+ and *target* Java 6 bytecode, but that doesn't prevent us from using JDK 7+ libraries accidentally in the future. Not sure how to handle that off the top of my head (without dropping TestNG...).

**Comment by ramesh4sr** [comment]
let me install jdk 6 and test this case

**Comment by Fireflies** [comment]
>Do we have support for jdk 6? A lot of applications are still running on jdk 6.

Applications **shouldn't** be running on JDK6 anymore as it was EOL'd eons ago. Even if an application targets 1.6 you should still be executing it in a more up-to-date JVM for obvious reasons, and thus should be able to use this library.

**Comment by Fireflies** [comment]
>Do we have support for jdk 6? A lot of applications are still running on jdk 6.

Applications should *not* be running on JDK6 as it was EOL'd eons ago. Instead they should be running on an up-to-date JVM where applicable and thus be able to utilise this library.

**Comment by bretthoerner** [comment]
In the end I don't see us supporting 6 when 7 is already EOL'd. Our test suite requires 7+ already and it's a struggle to use modern libraries that haven't required 8 for years.
