### ISSUE TITLE
coldfusion support

### ISSUE THREAD

**Issue by ashwin31** [getsentry/raven-java#203]
My web application is done in coldfusion railo. Does this raven support it? please guide me to documentation if it does.

@bretthoerner can you have a look at this please.

**Comment by dcramer** [comment]
If your coldfusion app is somehow running in the JVM and can import the Java SDK it will work, but as far as I know that's not true and thus the Java SDK would not be compatible

**Comment by bretthoerner** [comment]
I've never dealt with CF, but I searched and it seems that it does actually run on the JDK?

@ashwin31 if you're using SLF4J via CF, you should be able to use the appropriate Raven logger (logback, log4j, log4j2, jul) -- see the README in each subdirectory of the project.

If you aren't using SLF4J (or don't want to deal with integrating with logging) you can always use the `DefaultRavenFactory` to create a `Raven` object and manually send messages as necessary in your code using that object. That said, I have no idea how you use "regular" Java objects inside CF... :(
