### ISSUE TITLE
Remove Logback `minLevel` default parameter value.

### ISSUE THREAD

**Issue by tkaemming** [getsentry/raven-java#206]
We deprecated the `minLevel` parameter with f5ad3dcdf8e77dcee117487e233b51ffe1bc0219 because it duplicates the built-in filter functionality, but left the parameter's default value at warning level. Since this is no longer documented or recommended, we should remove the minimum level default.

We should also totally remove the parameter in the future (and figure out what the deprecation policy is for these kinds of things.)

**Comment by BillOTei** [comment]
as suggested for a temporary fix, using `<minLevel>_WHICHEVER-MINLEVEL-REQUIRED_</minLevel>` in the logback.xml configuration file for the appender tag fixes allows to send lower level events.
