### ISSUE TITLE
SHUTDOWN_TIMEOUT in AsyncConnection

### ISSUE THREAD

**Issue by zsoca8711** [getsentry/raven-java#209]
Hi,

i would like to ask why SHUTDOWN_TIMEOUT is not configurable and why it is set to 1 second?

Our usecase:
* Batch processing applications running from cron on CentOS
* The cron starts a shell script which starts the java app (so starts a JVM)
* I use sentry with default config with Log4j so i have Async connections
* When i wanted to test the app, i've set the Sentry Treshold to DEBUG
* This meant that the app finished before 61 tasks were submitted to Sentry

Even though i appreciate that on proper live settings i wouldn't have 61 tasks to push to sentry (god, i hope i wouldn't :D ) but that doesn't mean there is no potential risk of data loss here. Even if i have 1 task and for some reason, that takes more than a second to finish, it may mean i don't get notified about it.

**Comment by bretthoerner** [comment]
I don't see any reason why we couldn't make it configurable. I'll put it on my list unless you beat me to it. :)

**Comment by zsoca8711** [comment]
You beat me to it.
I'm not familiar with the source code, but will you accept pull requests on it? If so, do you have coding standards documented somewhere?
I'm saying i'll definitely do it, but maybe if i find some time.

**Comment by bretthoerner** [comment]
We definitely accept PRs, but this was an easy one.

**Comment by zsoca8711** [comment]
Oh, i haven't seen you actually done it as well. Thanks in that case.

**Comment by bretthoerner** [comment]
https://github.com/getsentry/raven-java/commit/a5b4ab5942857ecf19521a9709eeefa781575757

**Comment by bretthoerner** [comment]
@zsoca8711 This has been released in 7.2.3 (which is syncing to mirrors now).

**Comment by zsoca8711** [comment]
Amazing work. Thanks.
