### ISSUE TITLE
Raven send API inconsistency

### ISSUE THREAD

**Issue by AlexTrotsenko** [getsentry/raven-java#213]
I have my own EventBuilderHelper
```.JAVA
class UserInfoBuilderHelper implements EventBuilderHelper
```

I set it using 
```.JAVA
androidRaven.addBuilderHelper(userInfoBuilderHelper);
```

The problem, which I have if following:

When I call `Raven.sendException()` or `Raven.sendMessage()` 
my `UserInfoBuilderHelper` is executed and I see user info in the Sentry. 
But when I call `Raven.sendEvent()`  it's not called. 

From my understanding `.sendException()` and `.sendMessage()` should be simplified version of the `sendEvent()`. And that is why inner `BuilderHelper` should be executed also for the `sendEvent()` as well.

Following, is what I have to do in order to send "Warning" to the Sentry
```
        EventBuilder eventBuilder = new EventBuilder()
                .withSentryInterface(new ExceptionInterface(t))
                .withLevel(Level.WARNING);

        androidRaven.runBuilderHelpers(eventBuilder);

        androidRaven.sendEvent(eventBuilder.build());
```

Despite being verbose, it's also contradicts with builder pattern, as I have to call raven against builder, which modifies it.

If you really have any good reason to not execute helpers, which were set before, what about having another method like `.buildAndSendEvent(EventBuilder)` which will do so ?

**Comment by bretthoerner** [comment]
I agree it's a bit confusing, but the expectation (via the Javadoc) is that `sendEvent` is for sending a fully built `Event` object -- I don't think we should change that since it's been released for so long.

I can see the case for a `buildAndSendEvent` method though, any thoughts @tkaemming ?

**Comment by tkaemming** [comment]
Yeah, I think this is a reasonable concern.

I think that it would make sense to either:

* add a `public void buildAndSendEvent(EventBuilder)` method, or
* overload `buildEvent`, adding the `public void sendEvent(EventBuilder)` signature.

I guess my personal preference would be to just overload the method, mainly because the `buildAndSendEvent` name is a little long (so this is a purely stylistic preference, either one works.)

**Comment by bretthoerner** [comment]
Yeah, overloading makes a lot more sense: https://github.com/getsentry/raven-java/pull/218

**Comment by bretthoerner** [comment]
Closed with https://github.com/getsentry/raven-java/commit/deb7a83158f80a0ebc473121396244a5ec3955b4
