### ISSUE TITLE
Leaked Developer Credentials

### ISSUE THREAD

**Issue by Bruno-Furtado** [getsentry/raven-java#234]
**I received the following message on the Google Play Developer Console:**

> Your app has URL credential, which is generally not something intentional.

[The Google link](https://support.google.com/faqs/answer/7026406?hl=en) explains the problem.

-

I believe the alert is displayed because of that:

```java 
Sentry.init(this, "https://123:abc00@app.getsentry.com/98765");
```

-

How can I initialize the Sentry without this warning?

**Comment by tkaemming** [comment]
First off, to clarify (and for anyone who ends up here after Googling for this) the only thing that anyone can do with these credentials is send event data to your Sentry organization, not read data or perform other API requests on behalf of users of your organization.

Off of the top of my head, I'm not sure that we have any alternate methods of instantiating the client that doesn't utilize the keys as part of the DSN, but I'll check and follow up.

**Comment by Bruno-Furtado** [comment]
Ok... thanks @tkaemming!

**Comment by bretthoerner** [comment]
I believe `Sentry.init` is the only method currently (by my skim of the existing code, which is actually a different project entirely: https://github.com/joshdholtz/Sentry-Android).

I'm working on a new Android client right now, and you'll be able to provide init via a variable in your application manifest, although I don't think that will change the error. At the end of the day, as @tkaemming said, you'll need to ship this (rather harmless) key with your app in order for sending exceptions to work.

**Comment by Bruno-Furtado** [comment]
@bretthoerner,

Sorry, I opened an issue in the wrong repository.
[This issue](https://github.com/joshdholtz/Sentry-Android/issues/57), opened at [Sentry-Android](https://github.com/joshdholtz/Sentry-Android) repository, answers my question.

Thanks.
