### ISSUE TITLE
Incomplete JUL handler support for MDC/tags.

### ISSUE THREAD

**Issue by tkaemming** [getsentry/raven-java#237]
This is [documented as unsupported](https://github.com/getsentry/raven-java/tree/8207d186f0ab03c72d0ea04fec983251b68214c2/raven#unsupported-features), but most of the code actually exists to support this — we just need to add a configuration setter to allow this block to do anything: https://github.com/getsentry/raven-java/blob/8207d186f0ab03c72d0ea04fec983251b68214c2/raven/src/main/java/com/getsentry/raven/jul/SentryHandler.java#L259-L268

**Comment by bretthoerner** [comment]
This was https://github.com/getsentry/raven-java/pull/239 right?

**Comment by tkaemming** [comment]
Yep.
