### ISSUE TITLE
Add standard test base class

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/raven-java#243]
We have some global state that needs to be cleaned up between all test runs. The simplest thing would be to have all tests subclass from some base with this logic. TestNG may have other means to do this.

**Comment by tkaemming** [comment]
See also: GH-279, GH-238.

**Comment by bretthoerner** [comment]
https://github.com/getsentry/raven-java/pull/381/commits/8d89a234fe6759fd9a06db836ecbccd97512a79f
