### ISSUE TITLE
Raven.async=true, sentry server can not get data 

### ISSUE THREAD

**Issue by pengboyin** [getsentry/raven-java#247]
hi, when i set 'raven.async=true', sentry server can not get data,but when 'raven.async=false' the
sentry server can get data. i do not why, who can give me some proposal.
thanks :relaxed:

**Comment by bretthoerner** [comment]
Are these top level unhandled exceptions that kill your JVM process? If so, chances are the async sender doesn't have a chance to send the data before the entire process is killed.

I can't think of another case where this would happen...

**Comment by pengboyin** [comment]
Thank you, i found the reason, i do not set 'raven.async.shutdowntimeout', and the default is 1000, when executorService send data, it already shutdown.
