### ISSUE TITLE
Why there are apostrophes in header value?

### ISSUE THREAD

**Issue by pavelarnost** [getsentry/raven-java#248]
Hi,

why are header values wrapped in apostrophes? It looks ugly and inconsistent, there are not apostrophes in Cookies, Headers or Enviroment sections. Is this consistent with other Sentry.io platforms?

Regards
Pavel Arnošt

**Comment by bretthoerner** [comment]
This predates me, but it looks like it's to disambiguate between headers that are provided more than once, e.g.:

```
Header: foo
Header: bar
Header: foo, bar
```

Becomes:
```
Header: ' foo ', ' bar ', ' foo, bar'
```

Code here: https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/com/getsentry/raven/marshaller/json/HttpInterfaceBinding.java#L75

I just skimmed the Python client and it looks like we pass along whatever WSGI sets. https://github.com/getsentry/raven-python/blob/master/raven/utils/wsgi.py#L13-L24 It sounds like WSGI joins duplicates: https://stackoverflow.com/questions/1801124/how-does-wsgi-handle-multiple-request-headers-with-the-same-name

Section 4.2 of https://www.ietf.org/rfc/rfc2616.txt

>   Multiple message-header fields with the same field-name MAY be
>   present in a message if and only if the entire field-value for that
>   header field is defined as a comma-separated list [i.e., #(values)].
>   It MUST be possible to combine the multiple header fields into one
>   "field-name: field-value" pair, without changing the semantics of the
>   message, by appending each subsequent field-value to the first, each
>   separated by a comma. The order in which header fields with the same
>   field-name are received is therefore significant to the
>   interpretation of the combined field value, and thus a proxy MUST NOT
>   change the order of these field values when a message is forwarded.

So it sounds to me like we can drop apostrophes and combine duplicates with `,`? @tkaemming any thoughts?

**Comment by tkaemming** [comment]
I'll check today, but we store the headers as a sequence of `(name, value)` pairs, not as a mapping, so I think that we might just be able to pass along the duplicates as individual pairs.

**Comment by tkaemming** [comment]
Alright, I confirmed that the server will accept data as `(name, value)` pairs:

```json
"sentry.interfaces.Http": {
  "url": "http://example.com",
  "headers": [
    [
      "Referer",
      "foo"
    ],
    [
        "Referer",
        "bar"
    ]
  ],
  "method": "GET"
}
```

and render it as expected:

![screenshot 2016-09-02 16 38 28](https://cloud.githubusercontent.com/assets/65315/18220892/58601b8e-712b-11e6-8633-5ef6b3d32e4f.png)

So, let's move forward with that.

**Comment by pavelarnost** [comment]
Great, thanks.
