### ISSUE TITLE
How to pass extraTags recognized as user attributes

### ISSUE THREAD

**Issue by Enalmada** [getsentry/raven-java#259]
I love it when my browser errors show up linked to user context through passing user context to the javascript client 
```
Raven.setUserContext({
    email: 'foo@example.com'
});
```
I would expect something like this to map special extraTags reserved for user context:

logback:
   ```<extraTags>user.id, user.username, user.emailaddress, user.ip_address</extraTags>```

code:
   ```MDC.put("user.id", 12345)```

Sentry Interface:
   ```Users: 1```

How do we pass user context through logback MDC? 

This is critical for issues aggregation.  Without appropriate user context, it seems like tags with different user data will cause new issues to be created that are really the same thing from different user id.

**Comment by Ramblurr** [comment]
I think you need to add the [UserInterface](https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/com/getsentry/raven/event/interfaces/UserInterface.java) with your own `EventBuilderHelper`.

To do this you need to extend `DefaultRavenFactory` and call `   raven.addBuilderHelper(yourEventBuilderHelper);`

**Comment by bretthoerner** [comment]
@Ramblurr is correct from my reading of the issue, does that make sense to you @Enalmada? In your own `EventBuilderHelper` you can add the `UserInterface` that you desire -- for example: https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/com/getsentry/raven/event/helper/HttpEventBuilderHelper.java#L43

Thanks @Ramblurr

**Comment by Enalmada** [comment]
I do believe that info will be very useful for others looking to do aggregation of server errors based on user context.
 
For my specific case, I am using logback with Playframework/Scala framework which handles threads asynchronously....it is already a bit painful to even get MDC working with play ( http://yanns.github.io/blog/2014/05/04/slf4j-mapped-diagnostic-context-mdc-with-play-framework).  I am not sure how possible or it is for me to do my own EventBuilder.  

Can I request as a feature that raven-java reserves some extraTag keys like "user.id" and maps them the user id attributes?

**Comment by bretthoerner** [comment]
Ah I understand the issue with async frameworks. So you have MDC working? Which of the methods in that link did you use? I want to make sure I understand what would work for this and what wouldn't.

I'm a little scared to add special tag keys, but I'm sure we can figure something out.

**Comment by Enalmada** [comment]
Well I was going to try the first method where the MDC context is passed on.  But I too am scared of the performance and maintenance implications of needing custom code messing with every thread.  The more I think about that, the more I just want to back away slowly from this and not make eye contact.

If a good way to pass user context through mdc safely comes to you, I think it could be useful.  But for now I am going to close with a big thanks to everyone that help clarify our options right now.

**Comment by dlopuch** [comment]
I know this issue is closed, but for the google-bots, here's some code that implements this with a custom raven factory.  Solution is a bit unintuitive (for example, java lib doesn't allow for custom tags... had to do some reverse-engineering to figure out how to change the user interface to include it; requires custom json writing, etc).

```java
public class CustomTagsRavenFactory extends DefaultRavenFactory {
  @Override
  public Raven createRavenInstance(Dsn dsn) {
    Raven raven = super.createRavenInstance(dsn);

    raven.addBuilderHelper(new CustomUserCreatorEventBuilder());

    return raven;
  }

  @Override
  protected Marshaller createMarshaller(Dsn dsn) {
    JsonMarshaller marshaller = (JsonMarshaller) super.createMarshaller(dsn);

    // Need to define custom json writer for new user interface class
    marshaller.addInterfaceBinding(UserInterfaceWithExtraTags.class, new UserInterfaceWithExtraTagsBinding());

    return marshaller;
  }


  private class CustomUserCreatorEventBuilder implements EventBuilderHelper {
    private final RemoteAddressResolver remoteAddressResolver;

    public CustomUserCreatorEventBuilder() {
      this.remoteAddressResolver = new BasicRemoteAddressResolver();
    }

    @Override
    public void helpBuildingEvent(EventBuilder eventBuilder) {
      UserInterfaceWithExtraTags user;
      HttpServletRequest servletRequest = RavenServletRequestListener.getServletRequest();

      // <do what you need to do to extract user params from your web framework>
      user = new UserInterfaceWithExtraTags(...);

      eventBuilder.withSentryInterface(user);
    }
  }


  private class UserInterfaceWithExtraTags extends UserInterface {
    private Map<String, Object> extraTags = new HashMap<>();

    public UserInterfaceWithExtraTags(String id, String username, String ipAddress, String email) {
      super(id, username, ipAddress, email);
    }

    public UserInterfaceWithExtraTags addTag(String key, String value) {
      extraTags.put(key, value);
      return this;
    }

    public Map<String, Object> getTags() {
      return extraTags;
    }
  }


  private class UserInterfaceWithExtraTagsBinding implements InterfaceBinding<UserInterfaceWithExtraTags> {
    private static final String ID = "id";
    private static final String USERNAME = "username";
    private static final String EMAIL = "email";
    private static final String IP_ADDRESS = "ip_address";
    private static final String EXTRA_DATA = "data";

    @Override
    public void writeInterface(JsonGenerator generator, UserInterfaceWithExtraTags userInterface) throws IOException {
      generator.writeStartObject();
      generator.writeStringField(ID, userInterface.getId());
      generator.writeStringField(USERNAME, userInterface.getUsername());
      generator.writeStringField(EMAIL, userInterface.getEmail());
      generator.writeStringField(IP_ADDRESS, userInterface.getIpAddress());

      if (userInterface.getTags().size() > 0) {
        generator.writeObjectFieldStart(EXTRA_DATA);
        for (Map.Entry<String, Object> entry : userInterface.getTags().entrySet()) {
          generator.writeStringField(entry.getKey(), entry.getValue() == null ? null : entry.getValue().toString());
        }
        generator.writeEndObject();
      }

      generator.writeEndObject();
    }
  }
}
```

**Comment by bretthoerner** [comment]
Huh, @dlopuch do we actually render `data` on a user well in the UI, or did you just want this in your raw JSON payload? If extra user tags are generally useful I can add this to the project.

**Comment by dlopuch** [comment]
In the sentry webapp, anything in the data dictionary shows up as additional rows below the standard ID, Username, IP Address.  Makes it really helpful to show additional user params specific to your own business concerns.
