### ISSUE TITLE
Feature request: Reinitialize the raven instance

### ISSUE THREAD

**Issue by Ramblurr** [getsentry/raven-java#262]
We have our own `RavenFactory` that adds some `EventBuilder`s and customizes the `getNotInAppFrames` list. These EventBuilders require some beans injected via Spring so that they have access to the data they need to build the events (user information, session info, etc).

We're using the Log4j integration and the problem that arises is that Log4J initializes its appenders, along with Raven, before the Spring application context is ready. Moreover for the Spring magic to work correctly, we need Spring to instantiate the custom factory.

Thankfully, you all made the `raven` field in `SentryAppender` protected! So we can reinitialize it from a subclass.

Our workaround is to use a `SentryAppender` subclass, then pluck it from the `Logger` and set the spring-aware raven factory on it:

```
Appender appender = Logger.getRootLogger() .getAppender("SentryAppender");

if (appender == null)
    return;

SpringAwareSentryAppender sentryAppender = (SpringAwareSentryAppender) appender;
sentryAppender.setAnotherRavenFactory(customRavenFactory);
```

Of course, this workaround is brittle (fetching the appender by string) and feels hacky.

Is this the recommended solution to the problem of initializing raven later on in the app's boot? Or could we a come up with a nicer API?

**Comment by bretthoerner** [comment]
Interesting, this is a hard one given the chicken and egg problem...

I wonder if it'd be possible for you to *not* configure a `SentryAppender` in your configuration file, but to rather do it at runtime once your Spring stuff is ready? Something like this: http://stackoverflow.com/a/9003191

It's the only way I think of off the top of my head to cleanly solve the ordering issues here.

**Comment by bretthoerner** [comment]
I think the dynamic configuration in the comment above is the best bet. If this won't work for you feel free to re-open.

**Comment by Ramblurr** [comment]
@bretthoerner Yup, programmatically changing the appender works nicely. Thanks!
