### ISSUE TITLE
Filtering fields from generated Sentry issues

### ISSUE THREAD

**Issue by jackOfAiiTrades** [getsentry/raven-java#268]
Hey all - 

There is some data in the HttpInterface.parameters() (event.getSentryInterfaces().get("sentry.interfaces.Http") element that I don't want to be sent to Sentry, but I've been unable to determine how to filter these out.  

Is this something easy/possible to accomplish?  I couldn't find any info related to this with raven-java.

**Comment by bretthoerner** [comment]
I think your only hope for right now is to make a custom `RavenFactory` that doesn't add the HTTP interface (or adds a custom one of your making): https://github.com/getsentry/raven-java/#custom-ravenfactory

It looks like this is an existing TODO, you can see where it's added (and the method you should override) here: https://github.com/getsentry/raven-java/blob/master/raven/src/main/java/com/getsentry/raven/DefaultRavenFactory.java#L324-L327

**Comment by jackOfAiiTrades** [comment]
Hey thank you this is really helpful.  One thing that's unclear to me is how to get it to use the custom RavenFactory, do you have any idea how to do that?

**Comment by bretthoerner** [comment]
I need to update the documentation later this week, but the short of it is that you need to make a custom subclass of `RavenFactory` (you probably want to subclass `DefaultRavenFactory`), and then you need to tell your logging configuration to use it. For example see the `ravenFactory` parameter here for `logback`: https://github.com/getsentry/raven-java/tree/master/raven-logback#configuration-via-logbackxml

Lastly (and this is what I need to better document) you need to do number 2 here: https://github.com/getsentry/raven-java/issues/267#issuecomment-254359417
