### ISSUE TITLE
Exceptions being thrown in webapp when appender is not configured

### ISSUE THREAD

**Issue by ArloL** [getsentry/raven-java#269]
When raven-logback is present on the classpath the RavenServletContainerInitializer will always add RavenServletRequestListener to the ServletContext. If now I don't configure the raven-logback appender (for example an environment without sentry) [RavenServletRequestListener.java#L31](https://github.com/getsentry/raven-java/blob/2ddae94497bd48191eebdd1a44b149ef64b7cfa9/raven/src/main/java/com/getsentry/raven/servlet/RavenServletRequestListener.java#L31) throws a NullPointerException.

Typically raven is silent when it is not configured. Is this planned behavior or should there be no log message when there is no stored instance?

**Comment by bretthoerner** [comment]
That was definitely a mistake on my part, I've fixed it here: https://github.com/getsentry/raven-java/pull/270
