### ISSUE TITLE
Serializing an Event object using Java's serialization.

### ISSUE THREAD

**Issue by dkarchnak** [getsentry/raven-java#274]
Hello everyone,

I'm currently saving Events to files if an app fails to send them. Then I try to send them some other time. I'm using ObjectOutputStream.writeObject(Object) method, which uses Java's serialization. It works all correctly since Event class implements Serializable unless I add Breadcrumbs into the event. Breadcrumb class doesn't implement Serializable so I get a NotSerializableException when trying to serialize 'em. I think Breadcrumb class should implement Serializable as well as Event does. I don't know if there is any reason for this so I'm looking forward to hearing from you on this subject.

Thank you.

**Comment by bretthoerner** [comment]
That makes sense to me. By the way, we added first-class support for storing failed events to `raven` recently:

https://github.com/getsentry/raven-java#buffering-to-disk-upon-network-error

I'll fix the breadcrumbs issue.

**Comment by bretthoerner** [comment]
Fixed in PR, will release soon.

**Comment by dkarchnak** [comment]
@bretthoerner Thank you. I appreciate it so much :)
