### ISSUE TITLE
Event TTL

### ISSUE THREAD

**Issue by cmboult** [getsentry/raven-java#283]
Is it possible customise the TTL on events in Sentry? The docs say this is something important to consider but give no indication of where this should be set...

**Comment by tkaemming** [comment]
Where are you seeing this in the documentation? The only thing I can think of would be the `--days` argument for [sentry cleanup](https://docs.sentry.io/server/cli/cleanup/) on the server, or some other various TTLs for individual components (cache, TSDB, etc.) but these are all on the server side.
