### ISSUE TITLE
Don't throw exception on rate limiting

### ISSUE THREAD

**Issue by jackOfAiiTrades** [getsentry/raven-java#312]
This is a follow-up on:
https://github.com/getsentry/raven-java/issues/119

The concern I have is that in addition to spamming the logs with the sentry failure, it also prevents the printing of the actual error stack trace.

If we get a NPE on ClassA line 429, instead of seeing the stack trace for NPE on ClassA line 300, we see the rate limited error text. 

Is there any way to ensure that the stack trace of the actual application error gets logged?  We could have a ton of errors happen on ClassA to reach sentry limit, and then a bunch of errors on ClassB, then when we look in logs we'd have no idea about the ClassB failures.

**Comment by bretthoerner** [comment]
Is this also related to #291 ?

Are you using Sentry via a logging integration? It's odd to me that your exception would be swallowed. If you have a ConsoleAppender (for example) and the SentryAppender, your original exception should still go to *both*.

**Comment by jackOfAiiTrades** [comment]
It seems related to 291, although the OP doesn't seem to mention whether the original stack trace is also being printed or not.

Here is our log4j.xml
https://hastebin.com/uhokumobak.xml

**Comment by bretthoerner** [comment]
Hm, when I log an exception using a similar log4j setup I still see the original exception.

See the matching section in my gist:

```

https://gist.github.com/bretthoerner/890ea59211642fe882dd380ab020a634

**Comment by bretthoerner** [comment]
In the latest release (`7.8.3`) there is a new logger used specifically for Events that are dropped due to a lockdown, you can disable this logger in your logging framework of choice: `com.getsentry.raven.Raven.lockdown`

Let me know if you try this and have any issues. Note that we still log when a lockdown begins (or increases in backoff time), but with that logger above disabled you shouldn't receive log spam for *each* Event that fails.

**Comment by bretthoerner** [comment]
Quick update, my change didn't work with `AsyncConnection`, that was fixed here: https://github.com/getsentry/raven-java/commit/a74e8d74dbcadc0b7cf0098d01728677ee2cfe6f

Will be in the next release.

**Comment by adrian-baker** [comment]
> In the latest release (7.8.3) there is a new logger used specifically for Events that are dropped due to a lockdown

Did this logger survive the switch to io.sentry ? Log is filled with 429 exceptions .

**Comment by bretthoerner** [comment]
Yeah, it should be shown in the log messages. I believe it'd be `io.sentry.connection.AsyncConnection.lockdown`?

**Comment by adrian-baker** [comment]
Should I open a new issue, or is the same as https://github.com/getsentry/sentry-java/issues/545 ?

**Comment by bretthoerner** [comment]
So the code is written to log the first exception when Sentry tells the SDK to backoff. Subsequent exceptions while it is backed off go to the lockdown logger and would look like: `The connection to Sentry is currently locked down.`

https://github.com/getsentry/sentry-java/blob/f57a8e7020527ff077cff4400faabae631560289/sentry/src/main/java/io/sentry/connection/AsyncConnection.java#L171-L177

Are you seeing a spam of those logs back to back? Or are you seeing it log once every N minutes when the backoff period is over? You could always disable the `io.sentry.connection.AsyncConnection` logger, although I'm not sure how useful Sentry is if you're regularly being throttled. There's also a way to do client side event sampling if desired: https://docs.sentry.io/clients/java/config/#event-sampling

**Comment by adrian-baker** [comment]
Spam, in bursts.

Disabling the entire connection logger for sentry doesn't seem a good idea, as it would mask genuine connection errors.

I'll create a new issue to cover:
# backoff not working, at least for logging
# exceptions being logged unncessarily, which can't be suppressed

Previously we were using the older raven client with log4j, and only started seeing these issues when moving to sentry-logback.

**Comment by adrian-baker** [comment]
https://github.com/getsentry/sentry-java/issues/559
