### ISSUE TITLE
Include, remove and/or shrink core raven dependencies

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/raven-java#328]
This will break out to multiple issues/PRs but I think they're closely related and worth discussing in one place.

I think we need to:

1. Move any dependencies that we can out of the main `raven` submodule and into other submodules where they make more sense.  I think this means our use of ~~`org.slf4j` and~~ `javax.servlet` should move ~~(which also means moving the `java.util.logging` `SentryHandler` out to something like `raven-jul` since it references `slf4j`)~~. This isn't *strictly* required, but as it stands we have to tell Android users to configure Proguard to not warn for `javax.servlet.**` ~~and `org.slf4j.**`,~~ *and* we have to be super careful that any reference to those classes is wrapped to allow the class load to fail. I think it'd be better if they just weren't referenced in the `raven` module at all. UPDATE: Keeping `slf4j` for now as it is only 40K.

2. ~~Make sure we've chosen the smallest (in method count and bytes) dependencies possible that are still well written and maintained libraries that do what we need. This really only means `jackson`, as it's the only dependency we have that isn't there for a specific external API. There are smaller (and well maintained) JSON clients we can use, and we don't do anything that complex with JSON anyway.~~ UPDATE: Jackson turns out to be about ~250K, we're going to keep it for now.

3. Build standalone (dependencies shaded) jars alongside the normal ones. This has two benefits: a single jar to use Sentry -- useful for dropping a jar in a 3rd party `lib/` dir (Solr, ElasticSearch, Cassandra come to mind) -- and no collision of existing dependencies for users where this may be a problem. For example, we currently use Jackson `2.7.x` but `2.8.x` stable is out and some users may conflict here (which has happened to me).

**Comment by bretthoerner** [comment]
@tkaemming 💵 for your thoughts here

**Comment by tkaemming** [comment]
> 1. Move any dependencies that we can out of the main `raven` submodule and into other submodules where they make more sense.  I think this means our use of `org.slf4j` and `javax.servlet` should move, which also means moving the `java.util.logging` `SentryHandler` out to something like `raven-jul` since it references `slf4j`. This isn't *strictly* required, but as it stands we have to tell Android users to configure Proguard to not warn for `javax.servlet.**` and `org.slf4j.**`, *and* we have to be super careful that any reference to those classes is wrapped to allow the class load to fail. I think it'd be better if they just weren't referenced in the `raven` module at all.

The JUL bits make sense. I'm not sure how we'd cleanly (re)move the `javax.servlet` bits though.

> 2. Make sure we've chosen the smallest (in method count and bytes) dependencies possible that are still well written and maintained libraries that do what we need. This really only means `jackson`, as it's the only dependency we have that isn't there for a specific external API. There are smaller (and well maintained) JSON clients we can use, and we don't do anything that complex with JSON anyway.

👍 

> 3. Build standalone (dependencies shaded) jars alongside the normal ones. This has two benefits: a single jar to use Sentry -- useful for dropping a jar in a 3rd party `lib/` dir (Solr, ElasticSearch, Cassandra come to mind) -- and no collision of existing dependencies for users where this may be a problem. For example, we currently use Jackson `2.7.x` but `2.8.x` stable is out and some users may conflict here (which has happened to me).

👍

**Comment by bretthoerner** [comment]
> The JUL bits make sense. I'm not sure how we'd cleanly (re)move the javax.servlet bits though.

I think we need `raven-servlet` to contain that code and it can be managed via a ServiceLoader, because as we (eventually) add more frameworks etc I think they'll each have their own deps (for auto-breadcrumbs, contexts, and more) a la: https://github.com/openzipkin/brave

It's the Java way. 😞

**Comment by bretthoerner** [comment]
Broke out to issues.
