### ISSUE TITLE
Where is the automatic breadcrumb ?

### ISSUE THREAD

**Issue by helenamcfreire** [getsentry/raven-java#346]
Where can we enable automatic breadcrumb like this in swift?

https://github.com/getsentry/sentry-swift/blob/master/docs/advanced.rst

`SentryClient.shared?.enableAutomaticBreadcrumbTracking()`

**Comment by bretthoerner** [comment]
We're still working on this feature. Are you using Android, or a Java server-side framework?

**Comment by helenamcfreire** [comment]
Thanks for response.

Im using Android. Do you have a deadline already ?

**Comment by bretthoerner** [comment]
No timeline yet, but we're actively working on improving Android. I made a new ticket #347 if you want to follow it or if you have any advice on implementation.
