### ISSUE TITLE
Use AndroidEventBuilderHelper in RavenUncaughtExceptionHandler

### ISSUE THREAD

**Issue by ch-vadim-maximov** [getsentry/raven-java#363]
Right now no device info is sent by the exception handler. If you switch to AndroidEventBuilderHelper we get a lot more info to help debug the crash. Also it would be great if we can set some custom data to be sent with every crash.

**Comment by bretthoerner** [comment]
What version are you running? We send an `EventBuilder` which should run all the helpers. I'll have to do some further testing... https://github.com/getsentry/raven-java/blob/10ad5c9497ff5e292db506ac851a29d3e39e465d/raven-android/src/main/java/com/getsentry/raven/android/RavenUncaughtExceptionHandler.java#L51

As for custom data, do you mean something like setting app-level information (called tags elsewhere) like in #293 ?

**Comment by ch-vadim-maximov** [comment]
@bretthoerner Thanks for the reply! I'm running 7.8.1. Yes custom app-level data like in #293 but in crash events generated by the RavenUncaughtExceptionHandler.
From the SO post I figure I need to write custom RavenFactory and EventBuilders?

**Comment by bretthoerner** [comment]
Ahh, I think if you upgrade it will [fix your original problem](https://github.com/getsentry/raven-java/commit/10ad5c9497ff5e292db506ac851a29d3e39e465d). Let me know if it doesn't.

As for tags, yeah you override like the SO post said but I hope to add the feature natively soon.
