### ISSUE TITLE
EventBuilder - Expose getter for Event Level

### ISSUE THREAD

**Issue by anjo-swe** [getsentry/raven-java#372]
Use case: We only want to customize the fingerprint (e.g. add client name) when the Event Level isn't ERROR.

Example code that would be possible with the getter:

```
public class FingerprintEventBuilderHelper implements EventBuilderHelper {

    private static final String DEFAULT_FINGERPRINT = "{{ default }}";

    @Override
    public void helpBuildingEvent(EventBuilder eventBuilder) {
        String clientName = ThreadContext.get(CLIENT_NAME);
        if (clientName != null && eventBuilder.getEventLevel() != Event.Level.ERROR) {
            eventBuilder.withFingerprint(DEFAULT_FINGERPRINT, clientName);
        }
    }
}
```

**Comment by bretthoerner** [comment]
I've felt like the `EventBuilder` needed getters for a while now, too. One work around would be to build the event and then make a new `EventBuilder`. I'll try to add this soon.

**Comment by anjo-swe** [comment]
@bretthoerner want me to create a PR where we expose getters inside `EventBuilder`? Any specific requirements and/or tests that are needed?

**Comment by bretthoerner** [comment]
Yeah, that'd be great. I don't think we need tests for getters.

**Comment by anjo-swe** [comment]
PR created, exposed Event
