### ISSUE TITLE
Android error when compile with Proguard

### ISSUE THREAD

**Issue by VincenzoWiman** [getsentry/raven-java#373]
I try compile my app with proguard but i have this error. 

> Information:Gradle tasks [:app:assembleRelease]
Warning:com.getsentry.raven.servlet.RavenServletContainerInitializer: can't find superclass or interface javax.servlet.ServletContainerInitializer
Warning:com.getsentry.raven.servlet.RavenServletRequestListener: can't find superclass or interface javax.servlet.ServletRequestListener
Warning:com.getsentry.raven.config.JndiLookup: can't find referenced class javax.naming.InitialContext
Warning:com.getsentry.raven.config.JndiLookup: can't find referenced class javax.naming.Context
Warning:com.getsentry.raven.config.JndiLookup: can't find referenced class javax.naming.NoInitialContextException
Warning:com.getsentry.raven.config.JndiLookup: can't find referenced class javax.naming.NamingException
Warning:com.getsentry.raven.config.JndiLookup: can't find referenced class javax.naming.NoInitialContextException
Warning:com.getsentry.raven.config.JndiLookup: can't find referenced class javax.naming.NamingException
Warning:com.getsentry.raven.config.JndiLookup: can't find referenced class javax.naming.Context
Warning:com.getsentry.raven.config.JndiLookup: can't find referenced class javax.naming.NoInitialContextException
Warning:com.getsentry.raven.config.JndiLookup: can't find referenced class javax.naming.NamingException
Warning:com.getsentry.raven.event.helper.BasicRemoteAddressResolver: can't find referenced class javax.servlet.http.HttpServletRequest
Warning:com.getsentry.raven.event.helper.ForwardedAddressResolver: can't find referenced class javax.servlet.http.HttpServletRequest
Warning:com.getsentry.raven.event.helper.HttpEventBuilderHelper: can't find referenced class javax.servlet.http.HttpServletRequest
Warning:com.getsentry.raven.event.helper.RemoteAddressResolver: can't find referenced class javax.servlet.http.HttpServletRequest
Warning:com.getsentry.raven.event.interfaces.HttpInterface: can't find referenced class javax.servlet.http.HttpServletRequest
Warning:com.getsentry.raven.event.interfaces.HttpInterface: can't find referenced class javax.servlet.http.Cookie
Warning:com.getsentry.raven.event.interfaces.HttpInterface: can't find referenced class javax.servlet.http.HttpServletRequest
Warning:com.getsentry.raven.event.interfaces.HttpInterface: can't find referenced class javax.servlet.http.Cookie
Warning:com.getsentry.raven.event.interfaces.HttpInterface: can't find referenced class javax.servlet.http.HttpServletRequest
Warning:com.getsentry.raven.event.interfaces.HttpInterface: can't find referenced class javax.servlet.http.Cookie
Warning:com.getsentry.raven.event.interfaces.HttpInterface: can't find referenced class javax.servlet.http.HttpServletRequest
Warning:com.getsentry.raven.event.interfaces.HttpInterface: can't find referenced class javax.servlet.http.Cookie
Warning:com.getsentry.raven.event.interfaces.HttpInterface: can't find referenced class javax.servlet.http.HttpServletRequest
Warning:com.getsentry.raven.servlet.RavenServletContainerInitializer: can't find referenced class javax.servlet.ServletContext
Warning:com.getsentry.raven.servlet.RavenServletContainerInitializer: can't find referenced class javax.servlet.ServletContainerInitializer
Warning:com.getsentry.raven.servlet.RavenServletContainerInitializer: can't find referenced class javax.servlet.ServletException
Warning:com.getsentry.raven.servlet.RavenServletContainerInitializer: can't find referenced class javax.servlet.ServletContext
Warning:com.getsentry.raven.servlet.RavenServletRequestListener: can't find referenced class javax.servlet.http.HttpServletRequest
Warning:com.getsentry.raven.servlet.RavenServletRequestListener: can't find referenced class javax.servlet.ServletRequestEvent
Warning:com.getsentry.raven.servlet.RavenServletRequestListener: can't find referenced class javax.servlet.ServletRequestListener
Warning:com.getsentry.raven.servlet.RavenServletRequestListener: can't find referenced class javax.servlet.ServletRequest
Warning:com.getsentry.raven.servlet.RavenServletRequestListener: can't find referenced class javax.servlet.ServletRequestEvent
Warning:com.getsentry.raven.servlet.RavenServletRequestListener: can't find referenced class javax.servlet.http.HttpServletRequest
Warning:com.getsentry.raven.servlet.RavenServletRequestListener: can't find referenced class javax.servlet.ServletRequestEvent
Warning:com.getsentry.raven.servlet.RavenServletRequestListener: can't find referenced class javax.servlet.ServletRequest
Warning:org.slf4j.LoggerFactory: can't find referenced class org.slf4j.impl.StaticLoggerBinder
Warning:org.slf4j.MDC: can't find referenced class org.slf4j.impl.StaticMDCBinder
Warning:org.slf4j.MarkerFactory: can't find referenced class org.slf4j.impl.StaticMarkerBinder
Warning:there were 93 unresolved references to classes or interfaces.
Warning:Exception while processing task java.io.IOException: Please correct the above warnings first.
Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Job failed, see logs for details
Information:BUILD FAILED
Information:Total time: 8.65 secs
Information:1 error
Information:41 warnings
Information:See complete output in console

**Comment by bretthoerner** [comment]
Hi @VincenzoWiman, we don't actually support Proguard yet. You should be able to get your build to compile and run by adding the following to `app/proguard-rules.pro`:

```
-dontwarn javax.naming.**
-dontwarn javax.servlet.**
-dontwarn org.slf4j.**
```
But we need to add support for handling obfuscated code on both the build (client) side as well as the Sentry server side. We are tracking Proguard support in #317.
