### ISSUE TITLE
Google play warning about auth data

### ISSUE THREAD

**Issue by olegsm** [getsentry/raven-java#388]
Google play developer console has waring about private auth data in my app.
"com.getsentry.raven.dsn.Dsn: noop://user:password@localhost"

Could you please provide more friendly class member?
 public static final String DEFAULT_DSN = "noop://user:password@localhost:0/0";

Thanks.

**Comment by bretthoerner** [comment]
@olegsm Can you post the warning? I'm not sure how I need to change it in order to not trigger the warning.

**Comment by Hazer** [comment]
@bretthoerner I saw it before, Google [refers to their doc for more info](https://support.google.com/faqs/answer/7026406).

To sum up, basically they search for the [URL pattern for Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication#URL_encoding), not exactly words, but the URL pattern itself.

**Comment by bretthoerner** [comment]
Thanks @Hazer, I'll fix.
