### ISSUE TITLE
Store event builder helpers in a list?

### ISSUE THREAD

**Issue by kjkrum** [getsentry/raven-java#402]
`Raven` stores its event builder helpers in a `Set`:

    private final Set<EventBuilderHelper> builderHelpers =
        Collections.newSetFromMap(new ConcurrentHashMap<EventBuilderHelper, Boolean>());

Attempting to customize events by adding builder helpers is not reliable because the iteration order of a hash set is unspecified.

Additionally, the log messages suggest that helpers are already stored in a list:

    logger.debug("Adding '{}' to the list of builder helpers.", builderHelper);

Is there a reason why `builderHelpers` could not be changed to a `CopyOnWriteArrayList`?  The signature of `getBuilderHelpers()` couldn't be changed to return a `List`, but the method could still be made to work.

Alternatively, could the required concurrency be achieved with a `LinkedHashSet`, which does guarantee iteration order?

**Comment by bretthoerner** [comment]
We can change the type and signature in the coming `sentry-java` `1.0` release: #376

**Comment by bretthoerner** [comment]
Merged into 1.0 branch.
