### ISSUE TITLE
Typo in the documentation about extraTags

### ISSUE THREAD

**Issue by vgarmash** [getsentry/raven-java#405]
I found that while I was setting SENTRY_EXTRA_TAGS environment variable I was constantly getting null for `Lookup.lookup("extraTags");` Now I know why.

The lookup source code is doing the following:

```
// Try to obtain from a System Environment Variable
        if (value == null) {
            value = System.getenv("SENTRY_" + key.toUpperCase());
        }
```
Although [in the documentation ](https://docs.sentry.io/clients/java/modules/log4j2/) we see this variable name:

> SENTRY_EXTRA_TAGS	sentry.extratags	foo,bar,baz	Optional, provide tag names to be extracted from MDC

Correct environment variable name should be **SENTRY_EXTRATAGS**.

Please fix the documentation.

**Comment by bretthoerner** [comment]
Thanks, good catch: https://github.com/getsentry/raven-java/commit/6de740a8fe7e7ddf5789cd2c0dc391c1b772849f
