### ISSUE TITLE
Mark some "common" stackframes as not "in_app".

### ISSUE THREAD

**Issue by ColinHebert** [getsentry/raven-java#49]
I was wondering if it would be relevant to use the `in_app` parameter in the stacktrace interface in order to hide some of the most common stackframes.

The IDE I use for example automatically hides some parts of the stacktrace such as the `java.*` or `com.sun.*`.

Any thoughts?

Settings in IntelliJ (actually those are places where the debbuger won't try to step into, but the first elements of the list are relevant to that issue)
![Screen Shot 2013-04-05 at 15 52 29](https://f.cloud.github.com/assets/232139/344490/eefa1cd0-9e01-11e2-8127-7e0a80c299b3.png)

**Comment by PunKeel** [comment]
I would love it! :heart:

**Comment by bretthoerner** [comment]
This is configurable by subclassing `DefaultRavenFactory`: https://github.com/getsentry/raven-java/blob/cd55661ac830e3590a9216bb965c38f67710a6d7/raven/src/main/java/com/getsentry/raven/DefaultRavenFactory.java#L335-L351

I think some more common namespaces should probably be added, though.

**Comment by bretthoerner** [comment]
We're considering switching it from a blacklist to a whitelist. Default to nothing and urge users to tell us what namespace their app is in.

**Comment by ehthayer** [comment]
We did this in order to group stacktraces together and it resulted in better cohesiveness.  In fact, we're considering adding our 'in-app' stacktrace as a fingerprint.

**Comment by bretthoerner** [comment]
@ehthayer when you say you did "this" do you mean switching it to a whitelist?

**Comment by ehthayer** [comment]
yes, we switched to a whitelist so that the stacktrace paths we used in our hashing became more focused and less prone to incidental splittling.

**Comment by bretthoerner** [comment]
Great, thanks, it's good to hear that worked. I plan to switch the official SDK to do the same soon.

**Comment by bretthoerner** [comment]
Some more discussion of using this in event fingerprinting: https://forum.sentry.io/t/fingerprinting-with-whitelisted-stacktrace-class-and-line-number-path/938

**Comment by bretthoerner** [comment]
This was changed to a whitelist here: https://github.com/getsentry/raven-java/commit/27a66682410ff61c542c979bb31e5473758e027c

To be released in `8.0.0` in the next ~week I hope.
